title: Shivangi Prasad
description: Personal website

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-156524889-1

# Everything below here can be ignored, unless you want to change the theme entirely
#theme: minima
remote_theme: pmarsceill/just-the-docs

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

minima:
  skin: solarized
  social_links:
    github: shivangiphy
    linkedin: shivangiphy
    twitter: shivangiphy
